[tool.poetry]
name = "nsarchiver"
version = "0.1.0"
description = ""
authors = ["thiccaxe <51303986+thiccaxe@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
